/*
 * Copyright (c) 2020 Marco Zeuli
 * Licensed under MIT license.
 * For full license text, see LICENSE file in the repo root or https://opensource.org/licenses/MIT
 * If you would like to contribute https://github.com/maaaaarco/spaghetti-cmd-loader
 */

public inherited sharing class Constants {
  public static final String MDT_SUFFIX = '__mdt';
  public static final Set<String> MASTER_LABEL_FIELD_NAMES = new Set<String>{
    'MasterLabel',
    'Label'
  };
  public static final String DEVELOPER_NAME_FIELD_NAME = 'DeveloperName';
}
